export const ARCLOT_CONTRACT = {
  address: import.meta.env.VITE_CONTRACT_ADDRESS,
  abi: [
    { type: "constructor", inputs: [], stateMutability: "nonpayable" },
    { type: "receive", stateMutability: "payable" },
    {
      type: "function",
      name: "MAX_LEADERBOARD_SIZE",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "minBet",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "owner",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "playerEarnings",
      inputs: [{ name: "", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "playerStats",
      inputs: [{ name: "", type: "address", internalType: "address" }],
      outputs: [
        { name: "totalSpins", type: "uint256", internalType: "uint256" },
        { name: "totalWins", type: "uint256", internalType: "uint256" },
        { name: "totalPayout", type: "uint256", internalType: "uint256" },
        { name: "lastPayout", type: "uint256", internalType: "uint256" },
        {
          name: "totalBetAmount",
          type: "uint256",
          internalType: "uint256",
        },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "topPlayers",
      inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getLeaderboard",
      inputs: [],
      outputs: [
        {
          name: "",
          type: "tuple[]",
          internalType: "struct ArcClot.LeaderboardEntry[]",
          components: [
            { name: "player", type: "address", internalType: "address" },
            { name: "earnings", type: "uint256", internalType: "uint256" },
          ],
        },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getTopPlayers",
      inputs: [{ name: "count", type: "uint256", internalType: "uint256" }],
      outputs: [
        { name: "", type: "address[]", internalType: "address[]" },
        { name: "", type: "uint256[]", internalType: "uint256[]" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getPlayerRank",
      inputs: [{ name: "player", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getLeaderboardSize",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "setMinBet",
      inputs: [{ name: "_minBet", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "spin",
      inputs: [],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "withdraw",
      inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "event",
      name: "Spin",
      inputs: [
        {
          name: "player",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "result",
          type: "uint8[3]",
          indexed: false,
          internalType: "uint8[3]",
        },
        {
          name: "bet",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
        {
          name: "payout",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "LeaderboardUpdated",
      inputs: [
        {
          name: "player",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "earnings",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
        {
          name: "rank",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
  ],
};
